// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SFTPFileService manages SFTP sessions for remote file operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * Chmod changes the permission mode of a remote path.
 */
export function Chmod(id: string, remotePath: string, mode: number): $CancellablePromise<void> {
    return $Call.ByID(3052264246, id, remotePath, mode);
}

/**
 * Connect dials a new SSH connection and opens the SFTP subsystem.
 * It returns the new session id.
 */
export function Connect(opts: types$0.ConnectOptions): $CancellablePromise<string> {
    return $Call.ByID(3245728541, opts);
}

/**
 * Disconnect closes an SFTP session.
 */
export function Disconnect(id: string): $CancellablePromise<void> {
    return $Call.ByID(3454417951, id);
}

/**
 * Download copies a remote file or directory (recursively) to the local path.
 * Interrupted file transfers are resumed from the local file size.
 */
export function Download(id: string, remotePath: string, localPath: string): $CancellablePromise<void> {
    return $Call.ByID(3788473461, id, remotePath, localPath);
}

/**
 * Home returns the remote current directory.
 */
export function Home(id: string): $CancellablePromise<string> {
    return $Call.ByID(638370106, id);
}

/**
 * List returns the entries of a remote directory.
 */
export function List(id: string, remotePath: string): $CancellablePromise<types$0.FileEntry[] | null> {
    return $Call.ByID(3105636501, id, remotePath);
}

/**
 * Mkdir creates a remote directory (including missing parents).
 */
export function Mkdir(id: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(1146196116, id, remotePath);
}

/**
 * ReadFile reads a remote text file for the built-in editor, enforcing a size
 * limit and rejecting binary content.
 */
export function ReadFile(id: string, remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(1969051887, id, remotePath);
}

/**
 * Remove deletes a remote file or directory (recursively).
 */
export function Remove(id: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(2564437145, id, remotePath);
}

/**
 * Rename renames or moves a remote path.
 */
export function Rename(id: string, oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(3295465095, id, oldPath, newPath);
}

/**
 * Search walks a remote directory recursively and returns filename matches
 * (mode "name") or content matches (mode "content").
 */
export function Search(id: string, dir: string, pattern: string, mode: string): $CancellablePromise<types$0.SearchResult[] | null> {
    return $Call.ByID(2768692821, id, dir, pattern, mode);
}

/**
 * Stat returns information about a remote path.
 */
export function Stat(id: string, remotePath: string): $CancellablePromise<types$0.FileEntry | null> {
    return $Call.ByID(3229127723, id, remotePath);
}

/**
 * Upload copies a local file or directory (recursively) to the remote path.
 * Interrupted file transfers are resumed from the remote file size.
 */
export function Upload(id: string, localPath: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(1160532464, id, localPath, remotePath);
}

/**
 * WriteFile overwrites a remote text file with the given content.
 */
export function WriteFile(id: string, remotePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(2488285382, id, remotePath, content);
}
