// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalService manages interactive SSH terminal sessions.
 * Each session streams its output to the frontend through the
 * "terminal:output" event and announces termination with "terminal:exit".
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * Connect establishes an SSH connection and starts an interactive shell.
 * It returns the new session id.
 */
export function Connect(opts: types$0.ConnectOptions): $CancellablePromise<string> {
    return $Call.ByID(1711284433, opts);
}

/**
 * Disconnect closes the session and its underlying SSH connection.
 */
export function Disconnect(id: string): $CancellablePromise<void> {
    return $Call.ByID(1925460355, id);
}

/**
 * IsConnected reports whether the session is still alive.
 */
export function IsConnected(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(1554291496, id);
}

/**
 * KillProcess force-kills a remote process by PID.
 */
export function KillProcess(id: string, pid: number): $CancellablePromise<void> {
    return $Call.ByID(3799349342, id, pid);
}

/**
 * ProcessList returns the remote process table (Linux ps).
 */
export function ProcessList(id: string): $CancellablePromise<types$0.ProcessInfo[] | null> {
    return $Call.ByID(2965515150, id);
}

/**
 * Resize adjusts the remote PTY size (rows x cols).
 */
export function Resize(id: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(1749559641, id, rows, cols);
}

/**
 * RunCommand executes a command on the session's SSH connection (separate
 * channel, independent of the interactive PTY) and returns its combined
 * output. Commands that exit non-zero still return their output.
 */
export function RunCommand(id: string, command: string): $CancellablePromise<string> {
    return $Call.ByID(1760199651, id, command);
}

/**
 * ServerInfo queries basic server information (OS, CPU, memory, disks).
 * 内置重试机制：首次失败后会等待 800ms 重试一次，提高不稳定网络下的成功率。
 */
export function ServerInfo(id: string): $CancellablePromise<types$0.ServerInfo | null> {
    return $Call.ByID(2180983378, id);
}

/**
 * Write forwards terminal input (keystrokes) to the remote session.
 */
export function Write(id: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(2635601076, id, data);
}
