// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImportResult reports the outcome of an import.
 */
export interface ImportResult {
    "imported": number;
    "warnings": string[] | null;
}

/**
 * SshHost is a single importable host entry parsed from an SSH config.
 */
export interface SshHost {
    /**
     * Host 别名（作为连接名称）
     */
    "name": string;

    /**
     * 真实 IP / 域名
     */
    "hostName": string;
    "user": string;
    "port": number;

    /**
     * 私钥路径（可为空）
     */
    "identityFile": string;
}
