/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    ConnectDialog: typeof import('./src/components/ConnectDialog.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    CustomCommandsView: typeof import('./src/components/CustomCommandsView.vue')['default']
    DialogHost: typeof import('./src/components/DialogHost.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSplitter: typeof import('element-plus/es')['ElSplitter']
    ElSplitterPanel: typeof import('element-plus/es')['ElSplitterPanel']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    FilePanel: typeof import('./src/components/FilePanel.vue')['default']
    InputDialog: typeof import('./src/components/InputDialog.vue')['default']
    LocalTerminalPane: typeof import('./src/components/LocalTerminalPane.vue')['default']
    MarkdownEditor: typeof import('./src/components/MarkdownEditor.vue')['default']
    NetworkView: typeof import('./src/components/NetworkView.vue')['default']
    ProcessManagerView: typeof import('./src/components/ProcessManagerView.vue')['default']
    RemoteEditorPanel: typeof import('./src/components/RemoteEditorPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPanel: typeof import('./src/components/SearchPanel.vue')['default']
    ServerInfoView: typeof import('./src/components/ServerInfoView.vue')['default']
    SftpPanel: typeof import('./src/components/SftpPanel.vue')['default']
    SshConfigImport: typeof import('./src/components/SshConfigImport.vue')['default']
    TerminalPane: typeof import('./src/components/TerminalPane.vue')['default']
    TextEditor: typeof import('./src/components/TextEditor.vue')['default']
    TransferDock: typeof import('./src/components/TransferDock.vue')['default']
    TunnelView: typeof import('./src/components/TunnelView.vue')['default']
    UpdateDialog: typeof import('./src/components/UpdateDialog.vue')['default']
  }
}
