// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DocumentService exposes document CRUD + search to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * Create adds a new folder or file under parentID (0 = root) and returns it.
 */
export function Create(parentID: number, name: string, nodeType: string): $CancellablePromise<model$0.DocNode> {
    return $Call.ByID(3893971686, parentID, name, nodeType);
}

/**
 * Delete removes a node and all of its descendants.
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(256221069, id);
}

/**
 * GetContent returns the text content of a file node.
 */
export function GetContent(id: number): $CancellablePromise<string> {
    return $Call.ByID(853298239, id);
}

/**
 * List returns every document node without content (for building the tree),
 * ordered by sort then name.
 */
export function List(): $CancellablePromise<model$0.DocNode[] | null> {
    return $Call.ByID(131377262);
}

/**
 * Move moves a node to a new parent (0 = root). Moving a folder into its own
 * descendant is rejected.
 */
export function Move(id: number, newParentID: number): $CancellablePromise<void> {
    return $Call.ByID(3103455023, id, newParentID);
}

/**
 * Rename renames a node (same-name is a no-op; duplicates rejected).
 */
export function Rename(id: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(398479548, id, name);
}

/**
 * SaveContent overwrites the text content of a file node.
 */
export function SaveContent(id: number, content: string): $CancellablePromise<void> {
    return $Call.ByID(2372375560, id, content);
}

/**
 * Search searches the document tree by name (mode "name") or by file content
 * (mode "content").
 */
export function Search(pattern: string, mode: string): $CancellablePromise<types$0.SearchResult[] | null> {
    return $Call.ByID(3438513242, pattern, mode);
}
