// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes the configuration store to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * GetAll returns every stored setting as a key-value map.
 */
export function GetAll(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(3888200932);
}

/**
 * GetVersion returns the application version (injected at build time).
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(2549827255);
}

/**
 * Set stores (or updates) a setting value.
 */
export function Set(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(4140224569, key, value);
}
