// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DatabaseConfig describes a storage backend.
 */
export interface DatabaseConfig {
    /**
     * sqlite | mysql | postgres | sqlserver
     */
    "dialect": string;
    "host": string;
    "port": number;
    "username": string;
    "password": string;
    "database": string;

    /**
     * 附加连接参数（如 sslmode=require）
     */
    "params": string;

    /**
     * 同步密钥：多机共用同一密钥时，凭据可跨机解密
     */
    "syncKey": string;
}
