// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RestService exposes an HTTP request proxy to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * Send makes an HTTP request and returns the response synchronously.
 * All requests go through the Go net/http client, so there are no CORS
 * limitations from the WebView.
 */
export function Send(req: types$0.RestRequest): $CancellablePromise<types$0.RestResponse> {
    return $Call.ByID(3889539571, req);
}
