// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RestService exposes an HTTP request proxy and REST request management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * CreateFolder creates a new folder under parentID (0 = root).
 */
export function CreateFolder(parentID: number, name: string): $CancellablePromise<model$0.RestFolder> {
    return $Call.ByID(877759697, parentID, name);
}

/**
 * CreateRequest creates a new request under a folder (folderID 0 = root level).
 */
export function CreateRequest(folderID: number, name: string): $CancellablePromise<model$0.RestRequestModel> {
    return $Call.ByID(2554285862, folderID, name);
}

/**
 * DeleteEnvironment deletes an environment.
 */
export function DeleteEnvironment(id: number): $CancellablePromise<void> {
    return $Call.ByID(2939257139, id);
}

/**
 * DeleteNode deletes a folder (recursively) or a request.
 */
export function DeleteNode(id: number, nodeType: string): $CancellablePromise<void> {
    return $Call.ByID(937094274, id, nodeType);
}

/**
 * GetRequest returns the full content of a saved request.
 */
export function GetRequest(id: number): $CancellablePromise<types$0.RestItem> {
    return $Call.ByID(2480855692, id);
}

/**
 * ListChildren returns direct children of parentID (0 = root).
 * It returns a flat list of mixed folder + request nodes.
 */
export function ListChildren(parentID: number): $CancellablePromise<types$0.RestNode[] | null> {
    return $Call.ByID(1280034778, parentID);
}

/**
 * ListEnvironments returns all saved environments.
 */
export function ListEnvironments(): $CancellablePromise<types$0.RestEnvItem[] | null> {
    return $Call.ByID(965106131);
}

/**
 * MoveNode moves a folder or request to a new parent (newParentID = 0 for root).
 * Node type: "folder" for RestFolder, "request" for RestRequestModel.
 */
export function MoveNode(id: number, nodeType: string, newParentID: number, targetID: number, position: string): $CancellablePromise<void> {
    return $Call.ByID(2367905740, id, nodeType, newParentID, targetID, position);
}

/**
 * ReadStreamChunks polls accumulated stream data. Call repeatedly until Done.
 */
export function ReadStreamChunks(streamID: string): $CancellablePromise<types$0.StreamChunk> {
    return $Call.ByID(1582176711, streamID);
}

/**
 * RenameFolder renames a folder.
 */
export function RenameFolder(id: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(3806498827, id, name);
}

/**
 * RenameRequest renames a request.
 */
export function RenameRequest(id: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(407710560, id, name);
}

/**
 * SaveEnvironment creates or updates an environment.
 */
export function SaveEnvironment(env: types$0.RestSaveEnv): $CancellablePromise<types$0.RestEnvItem> {
    return $Call.ByID(1920594917, env);
}

/**
 * SaveRequest creates or updates a request.
 */
export function SaveRequest(req: types$0.RestSaveRequest): $CancellablePromise<types$0.RestItem> {
    return $Call.ByID(651947981, req);
}

/**
 * Send makes an HTTP request and returns the response synchronously.
 */
export function Send(req: types$0.RestRequest): $CancellablePromise<types$0.RestResponse> {
    return $Call.ByID(3889539571, req);
}

/**
 * SetDefaultEnvironment sets the default environment.
 */
export function SetDefaultEnvironment(id: number): $CancellablePromise<void> {
    return $Call.ByID(1978389345, id);
}

/**
 * StressTest runs a concurrent stress test with the given request.
 */
export function StressTest(req: types$0.StressTestRequest): $CancellablePromise<types$0.StressTestResult> {
    return $Call.ByID(4245447561, req);
}

/**
 * WSClose closes a WebSocket connection.
 */
export function WSClose(connID: string): $CancellablePromise<void> {
    return $Call.ByID(2240231993, connID);
}

/**
 * WSConnect dials a WebSocket server and returns a connection id.
 * Incoming messages are pushed directly to the frontend via the
 * "rest:ws:message" event (payload: {connId, type, data, time, sent}).
 */
export function WSConnect(req: types$0.WSConnectRequest): $CancellablePromise<types$0.WSConnectResult> {
    return $Call.ByID(745213431, req);
}

/**
 * WSReadMessages is kept for backwards compatibility with bindings generated
 * before the event-push refactor. Incoming messages are now delivered via
 * the "rest:ws:message" event, so this always returns an empty result.
 */
export function WSReadMessages(connID: string): $CancellablePromise<types$0.WSReadResult> {
    return $Call.ByID(1451615071, connID);
}

/**
 * WSSend sends a text message on an open WebSocket connection.
 */
export function WSSend(connID: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(2464474101, connID, message);
}
