// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectOptions describes a connection request for SSH terminal, SFTP or FTP sessions.
 */
export interface ConnectOptions {
    "host": string;
    "port": number;
    "username": string;
    "password": string;

    /**
     * UseKey enables public-key authentication; PrivateKey holds the PEM content
     * (RSA / EC / OPENSSH). Passphrase unlocks encrypted keys.
     */
    "useKey": boolean;
    "privateKey": string;
    "passphrase": string;

    /**
     * Terminal options (SSH only)
     */
    "rows": number;
    "cols": number;

    /**
     * remote shell to start, e.g. "/bin/bash"; empty = login shell
     */
    "shell": string;

    /**
     * FTP options
     * explicit FTPS
     */
    "tls": boolean;

    /**
     * skip TLS certificate verification
     */
    "insecure": boolean;

    /**
     * Optional initial remote directory for SFTP/FTP sessions
     */
    "defaultDir": string;

    /**
     * Optional pre-assigned session id (used to reuse an existing session)
     */
    "sessionId": string;
}

/**
 * DiskInfo describes one mounted filesystem (bytes).
 */
export interface DiskInfo {
    "mount": string;
    "size": number;
    "used": number;
    "avail": number;
    "usePercent": number;
}

/**
 * FileEntry describes one file system entry (local, SFTP or FTP).
 */
export interface FileEntry {
    "name": string;
    "path": string;
    "size": number;
    "mode": string;
    "modTime": string;
    "isDir": boolean;
    "symlink": boolean;
    "linkTarget"?: string;
}

/**
 * ProcessInfo describes one remote process (from ps).
 */
export interface ProcessInfo {
    "pid": number;
    "ppid": number;
    "user": string;
    "cpu": number;
    "mem": number;

    /**
     * KB
     */
    "rss": number;
    "stat": string;
    "command": string;
}

/**
 * ServerInfo describes basic facts about a remote server (Linux first).
 */
export interface ServerInfo {
    "hostname": string;
    "os": string;
    "kernel": string;
    "arch": string;
    "uptime": string;
    "cpuModel": string;
    "cpuCores": number;
    "load1": number;
    "load5": number;
    "load15": number;

    /**
     * bytes
     */
    "memoryTotal": number;

    /**
     * bytes
     */
    "memoryUsed": number;

    /**
     * bytes
     */
    "memoryAvail": number;
    "disks": DiskInfo[] | null;

    /**
     * 非 Linux 等提示
     */
    "error"?: string;
}

/**
 * SessionClosed is emitted when a connection dies (detected by keep-alive)
 * so the frontend can clear its session state.
 */
export interface SessionClosed {
    "sessionId": string;

    /**
     * sftp | ftp
     */
    "type": string;
    "reason"?: string;
}

/**
 * TerminalExit is emitted when an SSH terminal session ends.
 */
export interface TerminalExit {
    "sessionId": string;
    "code": number;
    "error"?: string;
}

/**
 * TerminalOutput is emitted to the frontend with chunks of SSH terminal output.
 */
export interface TerminalOutput {
    "sessionId": string;
    "data": string;
}

/**
 * TransferProgress is emitted while files are uploaded/downloaded.
 */
export interface TransferProgress {
    "sessionId": string;

    /**
     * upload | download
     */
    "op": string;
    "name": string;
    "done": number;
    "total": number;
}
