// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIChatDelta is emitted for each streamed chunk of a chat completion.
 */
export interface AIChatDelta {
    "requestId": string;
    "delta": string;
    "done": boolean;
    "error"?: string;
}

/**
 * AIConfig holds the user's AI provider settings. The API key is never
 * returned to the frontend; HasKey reports whether a key is stored.
 */
export interface AIConfig {
    "baseUrl": string;
    "model": string;
    "temperature": number;
    "maxTokens": number;
    "systemPrompt": string;
    "hasKey": boolean;
}

/**
 * AgentAsk asks the frontend to approve (or reject/edit) a proposed command.
 */
export interface AgentAsk {
    "sessionId": string;
    "step": number;
    "command": string;
    "reason": string;
    "why": string;
}

/**
 * AgentDone reports the agent turn completion.
 */
export interface AgentDone {
    "sessionId": string;
    "summary"?: string;
    "error"?: string;
}

/**
 * AgentOutput reports the result of an executed command.
 */
export interface AgentOutput {
    "sessionId": string;
    "step": number;
    "command": string;
    "output": string;
    "exitCode": number;
}

/**
 * AgentReply is a streamed AI text bubble in the terminal agent chat.
 */
export interface AgentReply {
    "sessionId": string;

    /**
     * 增量文本（Done 时为空）
     */
    "content": string;
    "done": boolean;
    "error"?: string;
}

/**
 * AgentStep reports the agent's lifecycle progress (proposed command,
 * execution started, rejected, or informational messages).
 */
export interface AgentStep {
    "sessionId": string;
    "step": number;

    /**
     * thinking | propose | running | rejected | blocked | info
     */
    "status": string;
    "command"?: string;
    "reason"?: string;
    "needsApproval": boolean;
    "why"?: string;
}

/**
 * ChatMessage is one turn in a chat conversation.
 */
export interface ChatMessage {
    /**
     * system | user | assistant
     */
    "role": string;
    "content": string;
}

/**
 * ConnectOptions describes a connection request for SSH terminal, SFTP or FTP sessions.
 */
export interface ConnectOptions {
    "host": string;
    "port": number;
    "username": string;
    "password": string;

    /**
     * UseKey enables public-key authentication; PrivateKey holds the PEM content
     * (RSA / EC / OPENSSH). Passphrase unlocks encrypted keys.
     */
    "useKey": boolean;
    "privateKey": string;
    "passphrase": string;

    /**
     * ForwardAgent enables SSH agent forwarding: the remote session can use the
     * local machine's SSH agent identities (SSH-only).
     */
    "forwardAgent": boolean;

    /**
     * Terminal options (SSH only)
     */
    "rows": number;
    "cols": number;

    /**
     * remote shell to start, e.g. "/bin/bash"; empty = login shell
     */
    "shell": string;

    /**
     * FTP options
     * explicit FTPS
     */
    "tls": boolean;

    /**
     * skip TLS certificate verification
     */
    "insecure": boolean;

    /**
     * Optional initial remote directory for SFTP/FTP sessions
     */
    "defaultDir": string;

    /**
     * Optional pre-assigned session id (used to reuse an existing session)
     */
    "sessionId": string;
}

/**
 * DiskInfo describes one mounted filesystem (bytes).
 */
export interface DiskInfo {
    "mount": string;
    "size": number;
    "used": number;
    "avail": number;
    "usePercent": number;
}

/**
 * FileEntry describes one file system entry (local, SFTP or FTP).
 */
export interface FileEntry {
    "name": string;
    "path": string;
    "size": number;
    "mode": string;
    "modTime": string;
    "isDir": boolean;
    "symlink": boolean;
    "linkTarget"?: string;
}

/**
 * IpStatus reports the remote host's IPs for the terminal status bar.
 */
export interface IpStatus {
    /**
     * 服务器网卡上的全部 IPv4（去重，不含回环/链路本地）
     */
    "ips": string[] | null;
}

/**
 * NetInterface describes one remote network interface.
 */
export interface NetInterface {
    "name": string;

    /**
     * up | down | unknown
     */
    "state": string;
    "mac": string;
    "mtu": number;
    "addresses": string[] | null;
    "rxBytes": number;
    "txBytes": number;
    "rxPackets": number;
    "txPackets": number;
}

/**
 * NetListener describes one listening socket on the remote host.
 */
export interface NetListener {
    /**
     * tcp | tcp6 | udp | udp6
     */
    "proto": string;

    /**
     * local address:port
     */
    "address": string;
    "pid": number;
    "process": string;
}

/**
 * NetRoute describes one routing table entry.
 */
export interface NetRoute {
    "destination": string;
    "gateway": string;
    "interface": string;
}

/**
 * NetworkInfo aggregates network facts about a remote server.
 * 监听端口已拆分为 NetworkListeners，避免较慢的 ss/netstat 拖累快速信息。
 */
export interface NetworkInfo {
    "interfaces": NetInterface[] | null;
    "routes": NetRoute[] | null;
    "dns": string[] | null;

    /**
     * 非 Linux 等提示
     */
    "error"?: string;
}

/**
 * ProcessInfo describes one remote process (from ps).
 */
export interface ProcessInfo {
    "pid": number;
    "ppid": number;
    "user": string;
    "cpu": number;
    "mem": number;

    /**
     * KB
     */
    "rss": number;
    "stat": string;
    "command": string;
}

/**
 * ReplaceResult reports the outcome of a replace-all operation.
 */
export interface ReplaceResult {
    /**
     * 被修改的文件数
     */
    "files": number;

    /**
     * 被替换的匹配总数
     */
    "occurrences": number;
}

/**
 * SearchOptions controls how search/replace matches text: case sensitivity,
 * whether the pattern is a regular expression (content mode only), and glob
 * patterns to exclude from the search (comma/newline separated).
 */
export interface SearchOptions {
    "caseSensitive": boolean;
    "useRegex": boolean;
    "exclude": string;
}

/**
 * SearchResult describes one search hit: either a filename match or a
 * content match (content matches also carry the line number and text).
 */
export interface SearchResult {
    "path": string;
    "name": string;
    "size": number;
    "modTime": string;
    "isDir": boolean;

    /**
     * Content search only
     */
    "lineNo"?: number;
    "line"?: string;
}

/**
 * ServerInfo describes basic facts about a remote server (Linux first).
 */
export interface ServerInfo {
    "hostname": string;
    "os": string;
    "kernel": string;
    "arch": string;
    "uptime": string;
    "cpuModel": string;
    "cpuCores": number;
    "load1": number;
    "load5": number;
    "load15": number;

    /**
     * bytes
     */
    "memoryTotal": number;

    /**
     * bytes
     */
    "memoryUsed": number;

    /**
     * bytes
     */
    "memoryAvail": number;
    "disks": DiskInfo[] | null;

    /**
     * 非 Linux 等提示
     */
    "error"?: string;
}

/**
 * SessionClosed is emitted when a connection dies (detected by keep-alive)
 * so the frontend can clear its session state.
 */
export interface SessionClosed {
    "sessionId": string;

    /**
     * sftp | ftp
     */
    "type": string;
    "reason"?: string;
}

/**
 * SystemForward describes one system-level (firewall NAT) port forwarding rule
 * on the remote host. 与会话转发（ssh -L/-R/-D）不同，这类规则由远端服务器的
 * 防火墙持久化，SSH 会话断开后依然生效。
 */
export interface SystemForward {
    /**
     * 规则标识（本应用创建=spark-fwd-xxx，其余为 sys-哈希）
     */
    "id": string;

    /**
     * tcp | udp
     */
    "proto": string;

    /**
     * 服务器对外监听端口
     */
    "srcPort": number;

    /**
     * 转发目标地址（IPv4）
     */
    "destIp": string;

    /**
     * 转发目标端口
     */
    "destPort": number;

    /**
     * 备注（记录在本应用的远端清单里）
     */
    "note"?: string;

    /**
     * firewalld | iptables | nftables
     */
    "backend": string;

    /**
     * firewalld 区域
     */
    "zone"?: string;

    /**
     * 由本应用创建（可整体撤销）
     */
    "managed": boolean;

    /**
     * 创建时间（本应用创建的规则）
     */
    "createdAt"?: string;

    /**
     * 原始规则文本，便于核对
     */
    "raw"?: string;
}

/**
 * SystemForwardRequest is the payload for creating one system forwarding rule.
 */
export interface SystemForwardRequest {
    /**
     * tcp | udp
     */
    "proto": string;

    /**
     * 服务器对外端口
     */
    "srcPort": number;

    /**
     * 目标 IPv4
     */
    "destIp": string;

    /**
     * 目标端口
     */
    "destPort": number;
    "note"?: string;

    /**
     * 仅 firewalld：区域，留空=默认区域
     */
    "zone"?: string;
}

/**
 * SystemForwardStatus is the remote firewall state shown in the 系统转发 panel.
 */
export interface SystemForwardStatus {
    /**
     * firewalld | iptables | nftables | none
     */
    "backend": string;

    /**
     * 展示用名称
     */
    "backendName": string;

    /**
     * 后端可用且具备权限
     */
    "available": boolean;

    /**
     * root | sudo | none
     */
    "privilege": string;

    /**
     * net.ipv4.ip_forward
     */
    "ipForward": boolean;

    /**
     * 持久化方式说明
     */
    "persist": string;
    "zone"?: string;

    /**
     * 本应用创建的规则数
     */
    "managed": number;

    /**
     * 全部转发规则数
     */
    "total": number;
    "rules": SystemForward[] | null;

    /**
     * 不可用原因 / 提示
     */
    "message"?: string;
}

/**
 * TerminalExit is emitted when an SSH terminal session ends.
 */
export interface TerminalExit {
    "sessionId": string;
    "code": number;
    "error"?: string;
}

/**
 * TerminalOutput is emitted to the frontend with chunks of SSH terminal output.
 */
export interface TerminalOutput {
    "sessionId": string;
    "data": string;
}

/**
 * TransferProgress is emitted while files are uploaded/downloaded.
 */
export interface TransferProgress {
    "sessionId": string;

    /**
     * upload | download
     */
    "op": string;
    "name": string;
    "done": number;
    "total": number;
}

/**
 * Tunnel describes one active SSH tunnel on a terminal session.
 */
export interface Tunnel {
    "id": string;

    /**
     * local | remote | socks
     */
    "kind": string;

    /**
     * 监听地址：local/socks=本机，remote=远端
     */
    "bindAddr": string;

    /**
     * 目标：local=远端目标，remote=本机目标，socks=空
     */
    "target": string;

    /**
     * running | stopped | error
     */
    "status": string;
    "error"?: string;
}
