// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HostKeyService manages the known_hosts database.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AcceptHostKey trusts the host's current key and stores it in known_hosts,
 * replacing any previous entry.
 */
export function AcceptHostKey(opts: types$0.ConnectOptions): $CancellablePromise<void> {
    return $Call.ByID(361911931, opts);
}

/**
 * CheckHostKey probes the host and reports whether its key is known,
 * unknown or mismatched.
 */
export function CheckHostKey(opts: types$0.ConnectOptions): $CancellablePromise<$models.HostKeyStatus | null> {
    return $Call.ByID(4145872619, opts);
}

/**
 * ListHostKeys returns all known_hosts entries.
 */
export function ListHostKeys(): $CancellablePromise<$models.HostKeyInfo[] | null> {
    return $Call.ByID(2872517628);
}

/**
 * RemoveHostKey deletes the known_hosts entry for the given host.
 */
export function RemoveHostKey(host: string, port: number): $CancellablePromise<void> {
    return $Call.ByID(2377625887, host, port);
}
