// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HostKeyInfo describes one entry in the known_hosts database.
 */
export interface HostKeyInfo {
    "host": string;
    "port": number;
    "fingerprint": string;
    "keyType": string;
}

/**
 * HostKeyStatus describes the verification result for a host's current key.
 */
export interface HostKeyStatus {
    "host": string;
    "port": number;

    /**
     * known | unknown | mismatch
     */
    "status": string;
    "fingerprint": string;
    "oldFingerprint"?: string;
    "keyType": string;
}
