// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LocalService provides local directory listing, dialogs and simple file ops.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * DefaultDownloadDir returns the user's Downloads folder (falls back to the
 * home directory). Used as the save location when the user cancels the
 * directory picker during a download.
 */
export function DefaultDownloadDir(): $CancellablePromise<string> {
    return $Call.ByID(2915207369);
}

/**
 * Home returns the current user's home directory.
 */
export function Home(): $CancellablePromise<string> {
    return $Call.ByID(967015330);
}

/**
 * List returns the entries of a local directory (directories first, then by name).
 */
export function List(dir: string): $CancellablePromise<types$0.FileEntry[] | null> {
    return $Call.ByID(2325698317, dir);
}

/**
 * Mkdir creates a local directory (including missing parents).
 */
export function Mkdir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(721176684, dir);
}

/**
 * PickDirectory opens a native directory chooser.
 */
export function PickDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2249934223);
}

/**
 * PickFiles opens a native multi-select file dialog for uploads.
 */
export function PickFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3856717843);
}

/**
 * PickOpenFile opens a native single-file dialog for reading a local file.
 */
export function PickOpenFile(title: string): $CancellablePromise<string> {
    return $Call.ByID(959602706, title);
}

/**
 * PickSaveFile opens a native save dialog with a suggested filename.
 */
export function PickSaveFile(defaultName: string): $CancellablePromise<string> {
    return $Call.ByID(4029933031, defaultName);
}

/**
 * ReadFile reads a local text file for the built-in editor, enforcing a size
 * limit and rejecting binary content.
 */
export function ReadFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(2180120455, path);
}

/**
 * ReadTextFile reads a local text file (supports leading ~ for home dir).
 */
export function ReadTextFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(3963761876, path);
}

/**
 * Remove deletes a local file or directory (recursively).
 */
export function Remove(p: string): $CancellablePromise<void> {
    return $Call.ByID(1265183281, p);
}

/**
 * Rename renames or moves a local path.
 */
export function Rename(oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(1485292127, oldPath, newPath);
}

/**
 * Search walks a local directory recursively and returns filename matches
 * (mode "name") or content matches (mode "content").
 */
export function Search(dir: string, pattern: string, mode: string): $CancellablePromise<types$0.SearchResult[] | null> {
    return $Call.ByID(3326553181, dir, pattern, mode);
}

/**
 * WriteFile writes text content to a local file.
 */
export function WriteFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3172815358, path, content);
}
