// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LocalService provides local directory listing, dialogs and simple file ops.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * Home returns the current user's home directory.
 */
export function Home(): $CancellablePromise<string> {
    return $Call.ByID(967015330);
}

/**
 * List returns the entries of a local directory (directories first, then by name).
 */
export function List(dir: string): $CancellablePromise<types$0.FileEntry[] | null> {
    return $Call.ByID(2325698317, dir);
}

/**
 * Mkdir creates a local directory (including missing parents).
 */
export function Mkdir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(721176684, dir);
}

/**
 * PickDirectory opens a native directory chooser.
 */
export function PickDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2249934223);
}

/**
 * PickFiles opens a native multi-select file dialog for uploads.
 */
export function PickFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3856717843);
}

/**
 * PickSaveFile opens a native save dialog with a suggested filename.
 */
export function PickSaveFile(defaultName: string): $CancellablePromise<string> {
    return $Call.ByID(4029933031, defaultName);
}

/**
 * Remove deletes a local file or directory (recursively).
 */
export function Remove(p: string): $CancellablePromise<void> {
    return $Call.ByID(1265183281, p);
}

/**
 * Rename renames or moves a local path.
 */
export function Rename(oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(1485292127, oldPath, newPath);
}
