// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FTPFileService manages FTP sessions for remote file operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * Connect establishes an FTP (or explicit FTPS) session and logs in.
 * It returns the new session id.
 */
export function Connect(opts: types$0.ConnectOptions): $CancellablePromise<string> {
    return $Call.ByID(2287909268, opts);
}

/**
 * Disconnect closes an FTP session.
 */
export function Disconnect(id: string): $CancellablePromise<void> {
    return $Call.ByID(3130181704, id);
}

/**
 * Download copies a remote file or directory (recursively) to the local path.
 * isDir tells the service the remote path is a directory (FTP LIST cannot be
 * reliably used to stat a single path). Interrupted file transfers resume
 * from the local file size (REST).
 */
export function Download(id: string, remotePath: string, localPath: string, isDir: boolean): $CancellablePromise<void> {
    return $Call.ByID(3370054446, id, remotePath, localPath, isDir);
}

/**
 * Home returns the remote current directory.
 */
export function Home(id: string): $CancellablePromise<string> {
    return $Call.ByID(977138985, id);
}

/**
 * List returns the entries of a remote directory.
 */
export function List(id: string, remotePath: string): $CancellablePromise<types$0.FileEntry[] | null> {
    return $Call.ByID(331391698, id, remotePath);
}

/**
 * Mkdir creates a remote directory (including missing parents).
 */
export function Mkdir(id: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(3852481093, id, remotePath);
}

/**
 * ReadFile reads a remote text file for the built-in editor, enforcing a size
 * limit and rejecting binary content.
 */
export function ReadFile(id: string, remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(3169044056, id, remotePath);
}

/**
 * Remove deletes a remote file or directory (recursively for directories).
 */
export function Remove(id: string, remotePath: string, isDir: boolean): $CancellablePromise<void> {
    return $Call.ByID(4081548482, id, remotePath, isDir);
}

/**
 * Rename renames or moves a remote path.
 */
export function Rename(id: string, oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(874951200, id, oldPath, newPath);
}

/**
 * Replace replaces every content match of pattern in files under dir,
 * returning how many files and occurrences were changed.
 */
export function Replace(id: string, dir: string, pattern: string, replacement: string, mode: string, opts: types$0.SearchOptions): $CancellablePromise<types$0.ReplaceResult> {
    return $Call.ByID(2416409778, id, dir, pattern, replacement, mode, opts);
}

/**
 * Search walks a remote directory recursively and returns filename matches
 * (mode "name") or content matches (mode "content"). opts controls case
 * sensitivity and regex (content only).
 */
export function Search(id: string, dir: string, pattern: string, mode: string, opts: types$0.SearchOptions): $CancellablePromise<types$0.SearchResult[] | null> {
    return $Call.ByID(3725900870, id, dir, pattern, mode, opts);
}

/**
 * Upload copies a local file or directory (recursively) to the remote path.
 * Interrupted file transfers resume from the remote file size (REST).
 */
export function Upload(id: string, localPath: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(1868093435, id, localPath, remotePath);
}

/**
 * WriteFile overwrites a remote text file with the given content (FTP STOR).
 */
export function WriteFile(id: string, remotePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(2251683975, id, remotePath, content);
}
