// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RestService exposes an HTTP request proxy and REST request management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * CreateFolder creates a new folder under parentID (0 = root).
 */
export function CreateFolder(parentID: number, name: string): $CancellablePromise<model$0.RestFolder> {
    return $Call.ByID(3720492972, parentID, name);
}

/**
 * CreateRequest creates a new request under a folder (folderID 0 = root level).
 */
export function CreateRequest(folderID: number, name: string): $CancellablePromise<model$0.RestRequestModel> {
    return $Call.ByID(2876657561, folderID, name);
}

/**
 * DeleteEnvironment deletes an environment.
 */
export function DeleteEnvironment(id: number): $CancellablePromise<void> {
    return $Call.ByID(958609456, id);
}

/**
 * DeleteNode deletes a folder (recursively) or a request.
 */
export function DeleteNode(id: number, nodeType: string): $CancellablePromise<void> {
    return $Call.ByID(3529467703, id, nodeType);
}

/**
 * GetEffectiveBaseURL walks up the folder hierarchy and returns the nearest
 * non-empty BaseURL. Returns empty string if no folder in the chain has a
 * BaseURL set.
 */
export function GetEffectiveBaseURL(folderID: number): $CancellablePromise<string> {
    return $Call.ByID(194547577, folderID);
}

/**
 * GetEffectiveCommonHeaders walks up the folder hierarchy and returns merged
 * common headers (closer folders override ancestor keys).
 */
export function GetEffectiveCommonHeaders(folderID: number): $CancellablePromise<types$0.KV[] | null> {
    return $Call.ByID(2988014454, folderID);
}

/**
 * GetRequest returns the full content of a saved request.
 */
export function GetRequest(id: number): $CancellablePromise<types$0.RestItem> {
    return $Call.ByID(2815680121, id);
}

/**
 * ListChildren returns direct children of parentID (0 = root).
 * It returns a flat list of mixed folder + request nodes.
 */
export function ListChildren(parentID: number): $CancellablePromise<types$0.RestNode[] | null> {
    return $Call.ByID(956485475, parentID);
}

/**
 * ListEnvironments returns all saved environments.
 */
export function ListEnvironments(): $CancellablePromise<types$0.RestEnvItem[] | null> {
    return $Call.ByID(2723276882);
}

/**
 * MoveNode moves a folder or request to a new parent (newParentID = 0 for root).
 * Node type: "folder" for RestFolder, "request" for RestRequestModel.
 */
export function MoveNode(id: number, nodeType: string, newParentID: number, targetID: number, position: string): $CancellablePromise<void> {
    return $Call.ByID(1918302641, id, nodeType, newParentID, targetID, position);
}

/**
 * ReadStreamChunks polls accumulated stream data. Call repeatedly until Done.
 */
export function ReadStreamChunks(streamID: string): $CancellablePromise<types$0.StreamChunk> {
    return $Call.ByID(1179165082, streamID);
}

/**
 * RenameFolder renames a folder.
 */
export function RenameFolder(id: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(1168903854, id, name);
}

/**
 * RenameRequest renames a request.
 */
export function RenameRequest(id: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(3129353907, id, name);
}

/**
 * SaveEnvironment creates or updates an environment.
 */
export function SaveEnvironment(env: types$0.RestSaveEnv): $CancellablePromise<types$0.RestEnvItem> {
    return $Call.ByID(1458663342, env);
}

/**
 * SaveRequest creates or updates a request.
 */
export function SaveRequest(req: types$0.RestSaveRequest): $CancellablePromise<types$0.RestItem> {
    return $Call.ByID(1165352030, req);
}

/**
 * Send makes an HTTP request and returns the response synchronously.
 */
export function Send(req: types$0.RestRequest): $CancellablePromise<types$0.RestResponse> {
    return $Call.ByID(1927950274, req);
}

/**
 * SetDefaultEnvironment sets the default environment.
 */
export function SetDefaultEnvironment(id: number): $CancellablePromise<void> {
    return $Call.ByID(1861131806, id);
}

/**
 * SetFolderBaseURL sets a folder's base URL. When empty, inherits from parent
 * folder or global environment.
 */
export function SetFolderBaseURL(id: number, baseURL: string): $CancellablePromise<void> {
    return $Call.ByID(2109829790, id, baseURL);
}

/**
 * SetFolderCommonHeaders sets a folder's common headers (JSON string).
 */
export function SetFolderCommonHeaders(id: number, headersJSON: string): $CancellablePromise<void> {
    return $Call.ByID(1506427533, id, headersJSON);
}

/**
 * SetRequestBaseURL sets a request's own base URL override.
 */
export function SetRequestBaseURL(id: number, baseURL: string): $CancellablePromise<void> {
    return $Call.ByID(3173194545, id, baseURL);
}

/**
 * StressTest runs a concurrent stress test with the given request.
 */
export function StressTest(req: types$0.StressTestRequest): $CancellablePromise<types$0.StressTestResult> {
    return $Call.ByID(434118444, req);
}

/**
 * WSClose closes a WebSocket connection.
 */
export function WSClose(connID: string): $CancellablePromise<void> {
    return $Call.ByID(669778146, connID);
}

/**
 * WSConnect dials a WebSocket server and returns a connection id.
 * Incoming messages are pushed directly to the frontend via the
 * "rest:ws:message" event (payload: {connId, type, data, time, sent}).
 */
export function WSConnect(req: types$0.WSConnectRequest): $CancellablePromise<types$0.WSConnectResult> {
    return $Call.ByID(3249010292, req);
}

/**
 * WSReadMessages is kept for backwards compatibility with bindings generated
 * before the event-push refactor. Incoming messages are now delivered via
 * the "rest:ws:message" event, so this always returns an empty result.
 */
export function WSReadMessages(connID: string): $CancellablePromise<types$0.WSReadResult> {
    return $Call.ByID(48693258, connID);
}

/**
 * WSSend sends a text message on an open WebSocket connection.
 */
export function WSSend(connID: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(1786107996, connID, message);
}
