// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SiteService exposes folder/site/link/account CRUD + URL opening.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseTunnel 关闭并释放一个隧道。
 */
export function CloseTunnel(id: string): $CancellablePromise<void> {
    return $Call.ByID(1372537333, id);
}

/**
 * CreateAccount creates an account under a link.
 */
export function CreateAccount(linkID: number, username: string, password: string, note: string): $CancellablePromise<model$0.SiteAccount> {
    return $Call.ByID(193598708, linkID, username, password, note);
}

/**
 * CreateFolder creates a folder under parentID (0 = root).
 */
export function CreateFolder(parentID: number, name: string): $CancellablePromise<model$0.SiteFolder> {
    return $Call.ByID(3640604261, parentID, name);
}

/**
 * CreateLink creates a link under a site. Name is optional; when empty it
 * defaults to the URL host.
 */
export function CreateLink(siteID: number, name: string, url: string, note: string): $CancellablePromise<model$0.SiteLink> {
    return $Call.ByID(2860162257, siteID, name, url, note);
}

/**
 * CreateSite creates a site under folderID (0 = root).
 */
export function CreateSite(folderID: number, name: string, note: string): $CancellablePromise<model$0.Site> {
    return $Call.ByID(2431219942, folderID, name, note);
}

/**
 * DeleteAccount removes an account.
 */
export function DeleteAccount(id: number): $CancellablePromise<void> {
    return $Call.ByID(1343086325, id);
}

/**
 * DeleteFolder removes a folder, its descendant folders, and the sites (with
 * their links/accounts) inside them.
 */
export function DeleteFolder(id: number): $CancellablePromise<void> {
    return $Call.ByID(2831540834, id);
}

/**
 * DeleteLink removes a link and its accounts.
 */
export function DeleteLink(id: number): $CancellablePromise<void> {
    return $Call.ByID(3075777266, id);
}

/**
 * DeleteSite removes a site and its links and accounts.
 */
export function DeleteSite(id: number): $CancellablePromise<void> {
    return $Call.ByID(2935782217, id);
}

/**
 * ListAccounts returns the accounts of a link (passwords decrypted).
 */
export function ListAccounts(linkID: number): $CancellablePromise<model$0.SiteAccount[] | null> {
    return $Call.ByID(3611298873, linkID);
}

/**
 * ListFolders returns all folder nodes (for building the tree).
 */
export function ListFolders(): $CancellablePromise<model$0.SiteFolder[] | null> {
    return $Call.ByID(3759091494);
}

/**
 * ListLinks returns the links of a site.
 */
export function ListLinks(siteID: number): $CancellablePromise<model$0.SiteLink[] | null> {
    return $Call.ByID(196226466, siteID);
}

/**
 * ListSites returns all sites (with their folderId).
 */
export function ListSites(): $CancellablePromise<model$0.Site[] | null> {
    return $Call.ByID(3061521211);
}

/**
 * ListTunnels 返回当前所有活动隧道，按建立顺序排列。
 */
export function ListTunnels(): $CancellablePromise<$models.TunnelInfo[] | null> {
    return $Call.ByID(2469273792);
}

/**
 * MoveFolder moves a folder to a new parent (cycle prevented). The folder is
 * appended to the end of the new parent.
 */
export function MoveFolder(id: number, newParentID: number): $CancellablePromise<void> {
    return $Call.ByID(855639504, id, newParentID);
}

/**
 * MoveSite moves a site to a different folder (0 = root). The site is appended
 * to the end of the new folder.
 */
export function MoveSite(id: number, newFolderID: number): $CancellablePromise<void> {
    return $Call.ByID(1783921151, id, newFolderID);
}

/**
 * OpenInApp opens a URL in a new in-app window (its own top-level WebView).
 * 顶层导航不受 iframe 反嵌入头（X-Frame-Options / CSP frame-ancestors）限制，
 * 证书错误由全局 --ignore-certificate-errors 忽略，POST / WebSocket 等交互也都正常，
 * 是打开宝塔面板等管理后台最可靠的方式。
 * 同一链接只保留一个窗口：已存在时更新标题/地址并聚焦，避免重复开窗
 * （Wails「Multiple Windows」文档的最佳实践：给窗口命名 + GetByName 去重）。
 */
export function OpenInApp(url: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(244774793, url, title);
}

/**
 * OpenInBrowser opens a URL in the system default browser.
 */
export function OpenInBrowser(url: string): $CancellablePromise<void> {
    return $Call.ByID(855881918, url);
}

/**
 * OpenTunnel 通过已保存的 SSH 连接建立本地端口转发：占用一个本机端口，
 * 把访问该端口的 TCP 流经 SSH 转发到 targetURL 指向的 host:port（在服务器侧解析）。
 * 同一个「连接 + 目标」已有活动隧道时直接复用，不会重复建连 / 重复开标签页。
 */
export function OpenTunnel(connectionID: number, targetURL: string): $CancellablePromise<$models.TunnelInfo> {
    return $Call.ByID(3104496299, connectionID, targetURL);
}

/**
 * ProxyBase returns the local proxy base URL, starting the proxy on first use.
 */
export function ProxyBase(): $CancellablePromise<string> {
    return $Call.ByID(2055684534);
}

/**
 * ProxyUrl converts a raw URL into a proxy URL for the embedded iframe.
 */
export function ProxyUrl(raw: string): $CancellablePromise<string> {
    return $Call.ByID(3322162876, raw);
}

/**
 * RenameFolder renames a folder.
 */
export function RenameFolder(id: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(678872487, id, name);
}

/**
 * ReorderFolder moves a folder to newParentID and positions it before/after
 * targetID among sibling folders (targetID == 0 appends at the end). Sibling
 * Sort values are rewritten to a contiguous 0..n range afterwards.
 */
export function ReorderFolder(id: number, newParentID: number, targetID: number, position: string): $CancellablePromise<void> {
    return $Call.ByID(491680380, id, newParentID, targetID, position);
}

/**
 * ReorderSite moves a site to newFolderID and positions it before/after
 * targetID among sibling sites (targetID == 0 appends at the end). Sibling Sort
 * values are rewritten to a contiguous 0..n range afterwards.
 */
export function ReorderSite(id: number, newFolderID: number, targetID: number, position: string): $CancellablePromise<void> {
    return $Call.ByID(2652912899, id, newFolderID, targetID, position);
}

/**
 * UpdateAccount updates an account.
 */
export function UpdateAccount(id: number, username: string, password: string, note: string): $CancellablePromise<model$0.SiteAccount> {
    return $Call.ByID(3122464811, id, username, password, note);
}

/**
 * UpdateLink updates a link. Name is optional; when empty it defaults to the
 * URL host.
 */
export function UpdateLink(id: number, name: string, url: string, note: string): $CancellablePromise<model$0.SiteLink> {
    return $Call.ByID(646738068, id, name, url, note);
}

/**
 * UpdateSite updates a site's name / note.
 */
export function UpdateSite(id: number, name: string, note: string): $CancellablePromise<model$0.Site> {
    return $Call.ByID(2624151519, id, name, note);
}
