// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as types$0 from "../../../../../changeme/app/service/types/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "session:closed": types$0.SessionClosed;
            "terminal:exit": types$0.TerminalExit;
            "terminal:output": types$0.TerminalOutput;
            "transfer:progress": types$0.TransferProgress;
        }
    }
}
