// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnService exposes saved-connection CRUD to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create persists a new saved connection and returns it with its id.
 */
export function Create(conn: model$0.SavedConnection): $CancellablePromise<model$0.SavedConnection> {
    return $Call.ByID(264141816, conn);
}

/**
 * CreateGroup creates a new empty group.
 */
export function CreateGroup(name: string): $CancellablePromise<void> {
    return $Call.ByID(1863443899, name);
}

/**
 * Delete removes a saved connection by id.
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(1286157223, id);
}

/**
 * DeleteGroup removes a group and moves its connections back to "未分组".
 */
export function DeleteGroup(name: string): $CancellablePromise<void> {
    return $Call.ByID(2788416654, name);
}

/**
 * Get returns a saved connection by id.
 */
export function Get(id: number): $CancellablePromise<model$0.SavedConnection | null> {
    return $Call.ByID(1963346456, id);
}

/**
 * List returns all saved connections, most recently updated first.
 */
export function List(): $CancellablePromise<model$0.SavedConnection[] | null> {
    return $Call.ByID(2786294772);
}

/**
 * ListGroups returns all connection groups in sidebar order (creation order).
 */
export function ListGroups(): $CancellablePromise<model$0.ConnectionGroup[] | null> {
    return $Call.ByID(3420954172);
}

/**
 * RemoveDuplicates finds connections sharing the same host + type and keeps
 * one of each group: the reachable one with the highest id if any is
 * reachable, otherwise the highest id (the "last" created one).
 * 
 * deep=false uses a plain TCP dial to host:port (no credentials needed).
 * deep=true additionally performs a real login (SSH auth / FTP Login) so the
 * keep-decision also distinguishes credentials that still work. Deep checks
 * are slower and may trigger server-side login-failure policies.
 */
export function RemoveDuplicates(deep: boolean): $CancellablePromise<$models.DedupResult> {
    return $Call.ByID(2948822714, deep);
}

/**
 * RenameGroup renames a group and reassigns all its connections.
 */
export function RenameGroup(oldName: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(2505589505, oldName, newName);
}

/**
 * SetGroup reassigns a connection to a group without touching its (encrypted)
 * credential fields. An empty group means "未分组".
 */
export function SetGroup(id: number, group: string): $CancellablePromise<void> {
    return $Call.ByID(2280937655, id, group);
}

/**
 * Update persists changes to an existing saved connection.
 */
export function Update(conn: model$0.SavedConnection): $CancellablePromise<model$0.SavedConnection> {
    return $Call.ByID(1986708653, conn);
}
