// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DedupResult reports the outcome of RemoveDuplicates.
 */
export interface DedupResult {
    "removed": number;
    "summary": string[] | null;
}
