// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService keeps one conversation per SSH session.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Cancel stops the current turn.
 */
export function Cancel(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3352379695, sessionID);
}

/**
 * Clear resets the in-memory conversation for a session.
 */
export function Clear(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3680764422, sessionID);
}

/**
 * Respond feeds the user's approval decision back to a waiting agent turn.
 */
export function Respond(sessionID: string, approved: boolean, command: string): $CancellablePromise<void> {
    return $Call.ByID(2415159754, sessionID, approved, command);
}

/**
 * Send appends a user message to the session conversation and runs one agent turn.
 */
export function Send(sessionID: string, message: string, mode: string): $CancellablePromise<void> {
    return $Call.ByID(2159847395, sessionID, message, mode);
}
