// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionGroup records the user-defined groups that saved connections can
 * be organized into. The group name is the primary key; Sort controls the
 * order groups appear in the sidebar (created order, stable across renames).
 */
export interface ConnectionGroup {
    "name": string;
    "sort": number;
    "createdAt": string;
}

/**
 * CustomCommand stores a user-defined command that can be sent to the
 * interactive SSH terminal with one click.
 */
export interface CustomCommand {
    "id": number;
    "name": string;
    "command": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * DocNode is one node in the built-in document tree. Folders and files share
 * the same table; files carry their text content in Content.
 */
export interface DocNode {
    "id": number;

    /**
     * 0 = root
     */
    "parentId": number;
    "name": string;

    /**
     * "folder" | "file"
     */
    "type": string;
    "content": string;

    /**
     * Sort keeps siblings in a stable user-visible order (folders first is
     * applied on the frontend).
     */
    "sort": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * Favorite bookmarks a directory (remote or local) for quick navigation.
 * Kind: "remote" (belongs to a saved connection) or "local" (global local bookmarks).
 */
export interface Favorite {
    "id": number;

    /**
     * remote | local
     */
    "kind": string;
    "connectionId": number;
    "path": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * SavedConnection stores a connection profile (SSH terminal / SFTP / FTP)
 * so users can reconnect without retyping the details.
 * Sensitive fields (Password / Passphrase / PrivateKey) are encrypted with a
 * machine-bound AES key before being written to SQLite (see app/service/secure).
 */
export interface SavedConnection {
    "id": number;
    "name": string;

    /**
     * 分组名（空表示未分组）
     */
    "group": string;

    /**
     * ssh | ftp
     */
    "type": string;
    "host": string;
    "port": number;
    "username": string;
    "password": string;
    "useKey": boolean;

    /**
     * PEM content
     */
    "privateKey": string;
    "passphrase": string;
    "defaultDir": string;

    /**
     * FTP explicit TLS
     */
    "tls": boolean;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * Site is one website group (站点), sitting in a folder (or root).
 */
export interface Site {
    "id": number;

    /**
     * 0 = root
     */
    "folderId": number;
    "name": string;
    "note": string;
    "sort": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * SiteAccount is a username/password pair belonging to a link (账号). The
 * password is encrypted at rest (AES-256-GCM, same key as connections).
 */
export interface SiteAccount {
    "id": number;
    "linkId": number;
    "username": string;
    "password": string;
    "note": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * SiteFolder is a folder node in the site tree (multi-level, like documents).
 */
export interface SiteFolder {
    "id": number;

    /**
     * 0 = root
     */
    "parentId": number;
    "name": string;
    "sort": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * SiteLink is one URL belonging to a site (链接).
 */
export interface SiteLink {
    "id": number;
    "siteId": number;
    "name": string;
    "url": string;
    "note": string;
    "sort": number;
    "createdAt": string;
    "updatedAt": string;
}
