// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionGroup records the user-defined groups that saved connections can
 * be organized into. The group name is the primary key; Sort controls the
 * order groups appear in the sidebar (created order, stable across renames).
 */
export interface ConnectionGroup {
    "name": string;
    "sort": number;
    "createdAt": string;
}

/**
 * CustomCommand stores a user-defined command that can be sent to the
 * interactive SSH terminal with one click.
 */
export interface CustomCommand {
    "id": number;
    "name": string;
    "command": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * Favorite bookmarks a directory (remote or local) for quick navigation.
 * Kind: "remote" (belongs to a saved connection) or "local" (global local bookmarks).
 */
export interface Favorite {
    "id": number;

    /**
     * remote | local
     */
    "kind": string;
    "connectionId": number;
    "path": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * SavedConnection stores a connection profile (SSH terminal / SFTP / FTP)
 * so users can reconnect without retyping the details.
 * Sensitive fields (Password / Passphrase / PrivateKey) are encrypted with a
 * machine-bound AES key before being written to SQLite (see app/service/secure).
 */
export interface SavedConnection {
    "id": number;
    "name": string;

    /**
     * 分组名（空表示未分组）
     */
    "group": string;

    /**
     * ssh | ftp
     */
    "type": string;
    "host": string;
    "port": number;
    "username": string;
    "password": string;
    "useKey": boolean;

    /**
     * PEM content
     */
    "privateKey": string;
    "passphrase": string;
    "defaultDir": string;

    /**
     * FTP explicit TLS
     */
    "tls": boolean;
    "createdAt": string;
    "updatedAt": string;
}
