// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService keeps one conversation per SSH session.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Cancel stops the current turn.
 */
export function Cancel(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(896759122, sessionID);
}

/**
 * Clear resets the in-memory conversation for a session (含环境快照与工作目录)。
 */
export function Clear(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(498519269, sessionID);
}

/**
 * Respond feeds the user's approval decision back to a waiting agent turn.
 */
export function Respond(sessionID: string, approved: boolean, command: string): $CancellablePromise<void> {
    return $Call.ByID(2019376253, sessionID, approved, command);
}

/**
 * Send appends a user message to the session conversation and runs one agent turn.
 */
export function Send(sessionID: string, message: string, mode: string): $CancellablePromise<void> {
    return $Call.ByID(3760362678, sessionID, message, mode);
}
