// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TunnelInfo 描述一个已建立的 SSH 本地端口转发。
 */
export interface TunnelInfo {
    "id": string;
    "connectionName": string;

    /**
     * 远程目标 host:port
     */
    "target": string;

    /**
     * 可在本机浏览器打开的 URL
     */
    "localUrl": string;
}
