// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SiteService exposes folder/site/link/account CRUD + URL opening.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

/**
 * CreateAccount creates an account under a link.
 */
export function CreateAccount(linkID: number, username: string, password: string, note: string): $CancellablePromise<model$0.SiteAccount> {
    return $Call.ByID(2186486049, linkID, username, password, note);
}

/**
 * CreateFolder creates a folder under parentID (0 = root).
 */
export function CreateFolder(parentID: number, name: string): $CancellablePromise<model$0.SiteFolder> {
    return $Call.ByID(3186854446, parentID, name);
}

/**
 * CreateLink creates a link under a site. Name is optional; when empty it
 * defaults to the URL host.
 */
export function CreateLink(siteID: number, name: string, url: string, note: string): $CancellablePromise<model$0.SiteLink> {
    return $Call.ByID(1492938582, siteID, name, url, note);
}

/**
 * CreateSite creates a site under folderID (0 = root).
 */
export function CreateSite(folderID: number, name: string, note: string): $CancellablePromise<model$0.Site> {
    return $Call.ByID(2426436989, folderID, name, note);
}

/**
 * DeleteAccount removes an account.
 */
export function DeleteAccount(id: number): $CancellablePromise<void> {
    return $Call.ByID(1747390124, id);
}

/**
 * DeleteFolder removes a folder, its descendant folders, and the sites (with
 * their links/accounts) inside them.
 */
export function DeleteFolder(id: number): $CancellablePromise<void> {
    return $Call.ByID(1678249389, id);
}

/**
 * DeleteLink removes a link and its accounts.
 */
export function DeleteLink(id: number): $CancellablePromise<void> {
    return $Call.ByID(2508162521, id);
}

/**
 * DeleteSite removes a site and its links and accounts.
 */
export function DeleteSite(id: number): $CancellablePromise<void> {
    return $Call.ByID(1099788542, id);
}

/**
 * ListAccounts returns the accounts of a link (passwords decrypted).
 */
export function ListAccounts(linkID: number): $CancellablePromise<model$0.SiteAccount[] | null> {
    return $Call.ByID(2282682238, linkID);
}

/**
 * ListFolders returns all folder nodes (for building the tree).
 */
export function ListFolders(): $CancellablePromise<model$0.SiteFolder[] | null> {
    return $Call.ByID(3834006591);
}

/**
 * ListLinks returns the links of a site.
 */
export function ListLinks(siteID: number): $CancellablePromise<model$0.SiteLink[] | null> {
    return $Call.ByID(2133334391, siteID);
}

/**
 * ListSites returns all sites (with their folderId).
 */
export function ListSites(): $CancellablePromise<model$0.Site[] | null> {
    return $Call.ByID(924852338);
}

/**
 * MoveFolder moves a folder to a new parent (cycle prevented).
 */
export function MoveFolder(id: number, newParentID: number): $CancellablePromise<void> {
    return $Call.ByID(3392625395, id, newParentID);
}

/**
 * MoveSite moves a site to a different folder (0 = root).
 */
export function MoveSite(id: number, newFolderID: number): $CancellablePromise<void> {
    return $Call.ByID(1144627372, id, newFolderID);
}

/**
 * OpenInApp opens a URL in a new in-app window (its own WebView). Kept as an
 * alternative; the primary flow embeds the URL in the frontend instead.
 */
export function OpenInApp(url: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(4175553076, url, title);
}

/**
 * OpenInBrowser opens a URL in the system default browser.
 */
export function OpenInBrowser(url: string): $CancellablePromise<void> {
    return $Call.ByID(4140775303, url);
}

/**
 * ProxyBase returns the local proxy base URL, starting the proxy on first use.
 */
export function ProxyBase(): $CancellablePromise<string> {
    return $Call.ByID(12053995);
}

/**
 * ProxyUrl converts a raw URL into a proxy URL for the embedded iframe.
 */
export function ProxyUrl(raw: string): $CancellablePromise<string> {
    return $Call.ByID(1087667095, raw);
}

/**
 * RenameFolder renames a folder.
 */
export function RenameFolder(id: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(4056522784, id, name);
}

/**
 * UpdateAccount updates an account.
 */
export function UpdateAccount(id: number, username: string, password: string, note: string): $CancellablePromise<model$0.SiteAccount> {
    return $Call.ByID(2885857030, id, username, password, note);
}

/**
 * UpdateLink updates a link. Name is optional; when empty it defaults to the
 * URL host.
 */
export function UpdateLink(id: number, name: string, url: string, note: string): $CancellablePromise<model$0.SiteLink> {
    return $Call.ByID(152393927, id, name, url, note);
}

/**
 * UpdateSite updates a site's name / note.
 */
export function UpdateSite(id: number, name: string, note: string): $CancellablePromise<model$0.Site> {
    return $Call.ByID(868716328, id, name, note);
}
