// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LaunchRequest describes an "open in Spark" request from the shell context menu.
 */
export interface LaunchRequest {
    /**
     * "terminal" | "editor"
     */
    "kind": string;

    /**
     * absolute path (file or directory)
     */
    "path": string;

    /**
     * whether Path is a directory
     */
    "isDir": boolean;
}
