// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DatabaseService exposes storage configuration to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExportConfig 把当前存储配置序列化成一段可分享的连接串，便于迁移到其他
 * 设备 / 重装后的安卓端。
 */
export function ExportConfig(): $CancellablePromise<string> {
    return $Call.ByID(433547766);
}

/**
 * GetCurrent returns the current storage config.
 */
export function GetCurrent(): $CancellablePromise<$models.DatabaseConfig> {
    return $Call.ByID(693830799);
}

/**
 * ImportConfig 解析 ExportConfig 导出的连接串，返回配置对象（不切换存储，
 * 由前端填入表单核对后走「保存并切换」）。
 */
export function ImportConfig(str: string): $CancellablePromise<$models.DatabaseConfig> {
    return $Call.ByID(2432575461, str);
}

/**
 * Switch makes the given database the active storage backend.
 * - 目标库为空：把当前数据迁移过去（凭据按新同步密钥重新加密），然后切换
 * - 目标库已有数据（例如多机同步时第二台机器加入）：只切换连接，不覆盖目标数据
 * 配置保存到本机文件（%APPDATA%\spark\dbconfig.json），重启后自动使用，无需重新设置。
 */
export function Switch(cfg: $models.DatabaseConfig): $CancellablePromise<void> {
    return $Call.ByID(3835402146, cfg);
}

/**
 * Test verifies that a connection to the given config can be established.
 */
export function Test(cfg: $models.DatabaseConfig): $CancellablePromise<void> {
    return $Call.ByID(277150522, cfg);
}
