// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DatabaseService exposes storage configuration to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetCurrent returns the current storage config.
 */
export function GetCurrent(): $CancellablePromise<$models.DatabaseConfig> {
    return $Call.ByID(693830799);
}

/**
 * Switch makes the given database the active storage backend.
 * - 目标库为空：把当前数据迁移过去（凭据按新同步密钥重新加密），然后切换
 * - 目标库已有数据（例如多机同步时第二台机器加入）：只切换连接，不覆盖目标数据
 * 配置保存到本机文件（%APPDATA%\spark\dbconfig.json），重启后自动使用，无需重新设置。
 */
export function Switch(cfg: $models.DatabaseConfig): $CancellablePromise<void> {
    return $Call.ByID(3835402146, cfg);
}

/**
 * Test verifies that a connection to the given config can be established.
 */
export function Test(cfg: $models.DatabaseConfig): $CancellablePromise<void> {
    return $Call.ByID(277150522, cfg);
}
