// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LocalService provides local directory listing, dialogs and simple file ops.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * DefaultDownloadDir returns the user's Downloads folder (falls back to the
 * home directory). Used as the save location when the user cancels the
 * directory picker during a download.
 */
export function DefaultDownloadDir(): $CancellablePromise<string> {
    return $Call.ByID(670724440);
}

/**
 * Home returns the current user's home directory.
 */
export function Home(): $CancellablePromise<string> {
    return $Call.ByID(2295154143);
}

/**
 * List returns the entries of a local directory (directories first, then by name).
 */
export function List(dir: string): $CancellablePromise<types$0.FileEntry[] | null> {
    return $Call.ByID(2554644096, dir);
}

/**
 * Mkdir creates a local directory (including missing parents).
 */
export function Mkdir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(1480918915, dir);
}

/**
 * PickDirectory opens a native directory chooser.
 */
export function PickDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2500958476);
}

/**
 * PickFiles opens a native multi-select file dialog for uploads.
 */
export function PickFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3327664812);
}

/**
 * PickOpenFile opens a native single-file dialog for reading a local file.
 */
export function PickOpenFile(title: string): $CancellablePromise<string> {
    return $Call.ByID(3320469403, title);
}

/**
 * PickSaveFile opens a native save dialog with a suggested filename.
 */
export function PickSaveFile(defaultName: string): $CancellablePromise<string> {
    return $Call.ByID(3239093266, defaultName);
}

/**
 * ReadFile reads a local text file for the built-in editor, enforcing a size
 * limit and rejecting binary content.
 */
export function ReadFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(1360915418, path);
}

/**
 * ReadTextFile reads a local text file (supports leading ~ for home dir).
 */
export function ReadTextFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(1981456741, path);
}

/**
 * Remove deletes a local file or directory (recursively).
 */
export function Remove(p: string): $CancellablePromise<void> {
    return $Call.ByID(2525512608, p);
}

/**
 * Rename renames or moves a local path.
 */
export function Rename(oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(1491993082, oldPath, newPath);
}

/**
 * Replace replaces every content match of pattern in files under dir,
 * returning how many files and occurrences were changed.
 */
export function Replace(dir: string, pattern: string, replacement: string, mode: string, opts: types$0.SearchOptions): $CancellablePromise<types$0.ReplaceResult> {
    return $Call.ByID(386673200, dir, pattern, replacement, mode, opts);
}

/**
 * Search walks a local directory recursively and returns filename matches
 * (mode "name") or content matches (mode "content"). opts controls case
 * sensitivity and regex (content only).
 */
export function Search(dir: string, pattern: string, mode: string, opts: types$0.SearchOptions): $CancellablePromise<types$0.SearchResult[] | null> {
    return $Call.ByID(2995439204, dir, pattern, mode, opts);
}

/**
 * WriteFile writes text content to a local file.
 */
export function WriteFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(73299993, path, content);
}
