// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LocalTerminalService manages local shell sessions.
 * Each session streams its output to the frontend through the
 * "localTerminal:output" event and announces termination with
 * "localTerminal:exit".
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Create spawns a local shell attached to a pseudo-terminal and returns a
 * new session id. shell 为空时使用平台默认 shell；可传 "powershell" 等覆盖。
 * rows / cols 为终端初始尺寸。
 */
export function Create(shell: string, rows: number, cols: number): $CancellablePromise<string> {
    return $Call.ByID(4196236269, shell, rows, cols);
}

/**
 * Disconnect terminates the local shell session.
 */
export function Disconnect(id: string): $CancellablePromise<void> {
    return $Call.ByID(2008753275, id);
}

/**
 * IsRunning reports whether the session is still alive.
 */
export function IsRunning(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(1632221676, id);
}

/**
 * Resize adjusts the local terminal size (rows x cols).
 */
export function Resize(id: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(3545503825, id, rows, cols);
}

/**
 * Write forwards terminal input (keystrokes) to the local shell.
 */
export function Write(id: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(1255736684, id, data);
}
