// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FavoriteService exposes favorite CRUD to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

/**
 * Create persists a new favorite (duplicates are rejected).
 */
export function Create(fav: model$0.Favorite): $CancellablePromise<model$0.Favorite> {
    return $Call.ByID(3893940390, fav);
}

/**
 * Delete removes a favorite by id.
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(2320357197, id);
}

/**
 * List returns the favorites of a kind ("remote"/"local") for a connection
 * (connectionID is 0 for local bookmarks), most recently added first.
 */
export function List(kind: string, connectionID: number): $CancellablePromise<model$0.Favorite[] | null> {
    return $Call.ByID(3478347822, kind, connectionID);
}
