// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIService exposes BYOK chat completions to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * Cancel stops an in-flight streaming request by id.
 */
export function Cancel(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(3441415423, requestID);
}

/**
 * ChatStream starts a streaming chat completion. Tokens are delivered to the
 * frontend through the "ai:delta" event keyed by requestID. This method
 * returns after the request is dispatched, or immediately with an error when
 * the configuration is incomplete; stream progress and completion arrive via
 * the event.
 */
export function ChatStream(requestID: string, messages: types$0.ChatMessage[] | null): $CancellablePromise<void> {
    return $Call.ByID(3251585599, requestID, messages);
}

/**
 * ClearKey removes the stored API key.
 */
export function ClearKey(): $CancellablePromise<void> {
    return $Call.ByID(809002509);
}

/**
 * Complete runs a one-shot (non-streaming) completion with an explicit system
 * prompt and returns the full reply text. Used by the terminal assistant,
 * editor actions and the document assistant.
 */
export function Complete(systemPrompt: string, userContent: string): $CancellablePromise<string> {
    return $Call.ByID(3564053374, systemPrompt, userContent);
}

/**
 * CompleteStream starts a one-shot streaming completion with an explicit
 * system prompt. Tokens are delivered through the "ai:delta" event keyed by
 * requestID — the same mechanism as ChatStream, but without prepending the
 * config's global system prompt.
 */
export function CompleteStream(requestID: string, systemPrompt: string, userContent: string): $CancellablePromise<void> {
    return $Call.ByID(1467083134, requestID, systemPrompt, userContent);
}

/**
 * GetConfig returns the current AI settings. The API key itself is never
 * exposed; HasKey reports whether one is stored.
 */
export function GetConfig(): $CancellablePromise<types$0.AIConfig> {
    return $Call.ByID(3374224241);
}

/**
 * SaveConfig persists AI settings. When apiKey is empty the previously stored
 * key is kept; when non-empty it replaces the stored key (encrypted).
 */
export function SaveConfig(cfg: types$0.AIConfig, apiKey: string): $CancellablePromise<void> {
    return $Call.ByID(3917761874, cfg, apiKey);
}
