// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateInfo describes the latest release compared with the running version.
 */
export interface UpdateInfo {
    "current": string;
    "latest": string;
    "hasUpdate": boolean;
    "name": string;
    "body": string;
}
