// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService exposes update checks and downloads to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckUpdate queries the GitHub Releases API and reports whether a newer
 * version exists. Network errors are returned as errors (the frontend treats
 * them as "check failed" and stays quiet).
 */
export function CheckUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(3829651524);
}

/**
 * DownloadUpdate downloads the latest release asset into the user's
 * Downloads folder (falling back to the home directory) and returns the
 * local file path. Progress is streamed through the "update:progress" event.
 */
export function DownloadUpdate(): $CancellablePromise<string> {
    return $Call.ByID(2670290070);
}

/**
 * LaunchApp starts a downloaded executable (e.g. the new version). The
 * current app keeps running; the user closes it and switches to the new one.
 */
export function LaunchApp(path: string): $CancellablePromise<void> {
    return $Call.ByID(2159267519, path);
}

/**
 * OpenReleasePage opens the GitHub release page in the system browser.
 */
export function OpenReleasePage(): $CancellablePromise<void> {
    return $Call.ByID(270586287);
}

/**
 * RevealInExplorer opens the file manager with the given path selected
 * (Windows: explorer /select,; other platforms open the parent folder).
 */
export function RevealInExplorer(path: string): $CancellablePromise<void> {
    return $Call.ByID(342653134, path);
}
