// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService exposes update checks and installs to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckUpdate checks for a newer release. When up to date it returns
 * HasUpdate=false with a nil error.
 */
export function CheckUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(3829651524);
}

/**
 * DownloadAndInstall downloads, verifies and stages the desktop update.
 */
export function DownloadAndInstall(): $CancellablePromise<void> {
    return $Call.ByID(1884888947);
}

/**
 * DownloadApk downloads the latest Android APK and returns its local path.
 */
export function DownloadApk(): $CancellablePromise<string> {
    return $Call.ByID(3952220183);
}

/**
 * OpenReleasePage opens the GitHub release page (system browser on desktop,
 * system intent on mobile).
 */
export function OpenReleasePage(): $CancellablePromise<void> {
    return $Call.ByID(270586287);
}

/**
 * Restart swaps the staged desktop binary into place and restarts the app.
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(2178145818);
}
