// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CustomCommandService exposes custom-command CRUD to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

/**
 * Create persists a new custom command and returns it with its id.
 */
export function Create(cmd: model$0.CustomCommand): $CancellablePromise<model$0.CustomCommand> {
    return $Call.ByID(865053800, cmd);
}

/**
 * Delete removes a custom command by id.
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(3383460343, id);
}

/**
 * List returns all custom commands, most recently updated first.
 */
export function List(): $CancellablePromise<model$0.CustomCommand[] | null> {
    return $Call.ByID(1660057444);
}

/**
 * Update persists changes to an existing custom command.
 */
export function Update(cmd: model$0.CustomCommand): $CancellablePromise<model$0.CustomCommand> {
    return $Call.ByID(3431865213, cmd);
}
