// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ShellMenuService holds a pending launch request until the frontend consumes
 * it. This covers the first-instance case where the request arrives before the
 * Vue frontend has mounted and subscribed to events; for later (second
 * instance) launches the request is also emitted live via the "app:open" event.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Consume returns and clears the pending launch request (nil if none).
 */
export function Consume(): $CancellablePromise<$models.LaunchRequest | null> {
    return $Call.ByID(1239235377);
}

/**
 * SetPending stores a request for the frontend to consume on startup.
 */
export function SetPending(r: $models.LaunchRequest | null): $CancellablePromise<void> {
    return $Call.ByID(368011474, r);
}
