// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes the configuration store to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * GetAll returns every stored setting as a key-value map.
 */
export function GetAll(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(532627461);
}

/**
 * GetVersion returns the application version (injected at build time).
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(1657103242);
}

/**
 * IsAutoStart reports whether the app is registered to start at login/boot.
 */
export function IsAutoStart(): $CancellablePromise<boolean> {
    return $Call.ByID(106233779);
}

/**
 * Set stores (or updates) a setting value.
 */
export function Set(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(1636900042, key, value);
}

/**
 * SetAutoStart enables or disables launching the app at login/boot.
 * 复用 Wails v3 内置的 AutostartManager（Windows 注册表 Run 键 / macOS
 * SMAppService 或 LaunchAgent / Linux autostart）。操作成功后把开关状态
 * 持久化到设置表，供下次启动恢复（见 main.go）。
 */
export function SetAutoStart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1250324383, enabled);
}

/**
 * SetTitleBarTheme 运行时切换 Windows 标题栏明暗。theme 为 "light" 或 "dark"。
 */
export function SetTitleBarTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(3140481422, theme);
}
