// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalService manages interactive SSH terminal sessions.
 * Each session streams its output to the frontend through the
 * "terminal:output" event and announces termination with "terminal:exit".
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * AddSystemForward 创建一条系统级（防火墙 NAT）端口转发规则并持久化。
 */
export function AddSystemForward(id: string, req: types$0.SystemForwardRequest): $CancellablePromise<types$0.SystemForwardStatus | null> {
    return $Call.ByID(424843423, id, req);
}

/**
 * CloseTunnel closes and releases a tunnel by id.
 */
export function CloseTunnel(tunnelID: string): $CancellablePromise<void> {
    return $Call.ByID(1349323798, tunnelID);
}

/**
 * Connect establishes an SSH connection and starts an interactive shell.
 * It returns the new session id.
 */
export function Connect(opts: types$0.ConnectOptions): $CancellablePromise<string> {
    return $Call.ByID(593194462, opts);
}

/**
 * Disconnect closes the session and its underlying SSH connection.
 */
export function Disconnect(id: string): $CancellablePromise<void> {
    return $Call.ByID(223124034, id);
}

/**
 * IpStatus gathers the remote host's IPv4 addresses (all, not just private),
 * for the terminal status bar.
 */
export function IpStatus(id: string): $CancellablePromise<types$0.IpStatus | null> {
    return $Call.ByID(2409998683, id);
}

/**
 * IsConnected reports whether the session is still alive.
 */
export function IsConnected(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(2813926199, id);
}

/**
 * KillProcess force-kills a remote process by PID.
 */
export function KillProcess(id: string, pid: number): $CancellablePromise<void> {
    return $Call.ByID(3153935621, id, pid);
}

/**
 * NetworkInfo gathers interfaces, routes and DNS. 内置重试：首次失败或拿到空数据
 * 时短暂等待后重试一次，降低不稳定网络下偶尔采集失败导致的界面闪烁。
 */
export function NetworkInfo(id: string): $CancellablePromise<types$0.NetworkInfo | null> {
    return $Call.ByID(1859893326, id);
}

/**
 * NetworkListeners returns the remote listening sockets (ss / netstat).
 */
export function NetworkListeners(id: string): $CancellablePromise<types$0.NetListener[] | null> {
    return $Call.ByID(2229413555, id);
}

/**
 * OpenTunnel establishes a tunnel on the given session.
 * kind ∈ {local, remote, socks}；bindAddr 为空或纯端口时默认 127.0.0.1（随机端口）。
 * socksUser/socksPass 仅对 socks 生效：非空时为 SOCKS5 启用用户名/密码认证。
 */
export function OpenTunnel(id: string, kind: string, bindAddr: string, target: string, socksUser: string, socksPass: string): $CancellablePromise<types$0.Tunnel> {
    return $Call.ByID(1962871946, id, kind, bindAddr, target, socksUser, socksPass);
}

/**
 * ProcessList returns the remote process table (Linux ps).
 */
export function ProcessList(id: string): $CancellablePromise<types$0.ProcessInfo[] | null> {
    return $Call.ByID(1006049921, id);
}

/**
 * RemoveSystemForward 删除一条系统转发规则（按规则 ID）。
 */
export function RemoveSystemForward(id: string, ruleID: string): $CancellablePromise<types$0.SystemForwardStatus | null> {
    return $Call.ByID(1251150590, id, ruleID);
}

/**
 * Resize adjusts the remote PTY size (rows x cols).
 */
export function Resize(id: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(2824122688, id, rows, cols);
}

/**
 * RunCommand executes a command on the session's SSH connection (separate
 * channel, independent of the interactive PTY) and returns its combined
 * output. Commands that exit non-zero still return their output.
 */
export function RunCommand(id: string, command: string): $CancellablePromise<string> {
    return $Call.ByID(2636071290, id, command);
}

/**
 * ServerInfo queries basic server information (OS, CPU, memory, disks).
 * 内置重试机制：首次失败后会短暂等待重试一次，提高不稳定网络下的成功率。
 */
export function ServerInfo(id: string): $CancellablePromise<types$0.ServerInfo | null> {
    return $Call.ByID(1522500935, id);
}

/**
 * SystemForwardStatus 探测远端防火墙后端、权限与已有的转发规则。
 */
export function SystemForwardStatus(id: string): $CancellablePromise<types$0.SystemForwardStatus | null> {
    return $Call.ByID(228901464, id);
}

/**
 * Tunnels returns all tunnels of a session, ordered by creation time.
 */
export function Tunnels(sessionID: string): $CancellablePromise<types$0.Tunnel[] | null> {
    return $Call.ByID(2393658835, sessionID);
}

/**
 * Write forwards terminal input (keystrokes) to the remote session.
 */
export function Write(id: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(3983376343, id, data);
}
