// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SshConfigService parses and imports OpenSSH client config.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DefaultConfigPath returns the platform SSH config path (~/.ssh/config).
 */
export function DefaultConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(481951055);
}

/**
 * Import creates saved connections for the given hosts. IdentityFile keys are
 * read from disk (with ~ expansion); unreadable keys fall back to password
 * auth. Existing connections with the same name are skipped.
 */
export function Import(hosts: $models.SshHost[] | null, group: string): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(3546333924, hosts, group);
}

/**
 * Parse parses OpenSSH config content into importable host entries.
 * Wildcard hosts (containing * ? !) are skipped. Keywords are case-insensitive.
 */
export function Parse(content: string): $CancellablePromise<$models.SshHost[] | null> {
    return $Call.ByID(29546076, content);
}
